#!/bin/sh
#
# Copyright (c) 2016, The Linux Foundation. All rights reserved.
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

. /lib/functions/boot.sh

pi_mount_skip_next=false
pi_jffs2_mount_success=false
pi_ext4_mount_success=false
pi_ubifs_mount_success=false

. /lib/initoverlay/check_overlay.sh
. /lib/initoverlay/mount_overlay.sh
. /lib/initoverlay/pivot_overlay.sh

do_initoverlay() {
	do_mount_overlay
}

case "${1}" in
	start)
		do_initoverlay
	;;
	*)
	echo "Usage: $0 {start}" >&2
		exit 3
	;;
esac
